on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Tag/Release on Push Action
        uses: rymndhng/release-on-push-action@v0.23.1
        with:
          bump_version_scheme: minor
          tag_prefix: v
          use_github_release_notes: true
          release_name: "Release <RELEASE_VERSION>"

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"